Repository MunteanuAndreiStefan/SoftwareEngineeringTechniques, pull requests merged in 2019-11, with the labels that each got.

#39 - made crawler functional and populated MongoDB with about 3k tweets …
  Architecture/src/TwitterScrapingModule/export_mongo_to_redis.py
  Architecture/src/TwitterScrapingModule/main.py
  Architecture/src/TwitterScrapingModule/process_tweets.py
Labels: enhancement

#38 Add BPMN Diagram
  Architecture/BPMN/diagram.bpmn
  Architecture/BPMN/diagram.png
  Architecture/BPMN/diagram.svg
Labels: documentation

#44 Gcrisnuta
  Architecture/src/TwitterScrapingModule/export_mongo_to_redis.py
  Architecture/src/TwitterScrapingModule/process_tweets.py
Labels: development
